### ISSUE TITLE
Unsupported API version: 1.10.2

### ISSUE THREAD

**Issue by eirikh1996** [TylerS1066/Movecraft-Combat#27]
Movecraft-Combat is not loading on 1.16.2.

```
[21:10:51] [Server thread/ERROR]: Could not load 'plugins\Movecraft-Combat-0.8.24.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.10.2
        at org.bukkit.craftbukkit.v1_16_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:284) ~[spigot-1.16.2.jar:git-Spigot-379750e-1e76d09]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.16.2.jar:git-Spigot-379750e-1e76d09]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.2.jar:git-Spigot-379750e-1e76d09]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.2.jar:git-Spigot-379750e-1e76d09]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:381) ~[spigot-1.16.2.jar:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:186) ~[spigot-1.16.2.jar:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.2.jar:git-Spigot-379750e-1e76d09]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-1e76d09]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

MCC version: 0.8.24
Server software: SpigotMC
Server version: 1.16.2

**Comment by TylerS1066** [comment]
Only MCC version 1.0.0-SNAPSHOTs have support for 1.13+.
