### ISSUE TITLE
Error occurred while enabling Movecraft-Combat v2.0.0-a.5 (Is it up to date?)

### ISSUE THREAD

**Issue by Redacted00** [TylerS1066/Movecraft-Combat#94]
Hello, I have a problem with a plugin.
Version 2.0.0 Alpha 5

Console: 
```
[08:25:08 ERROR]: Error occurred while enabling Movecraft-Combat v2.0.0-a.5 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.THIN_GLASS
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:92) ~[forge:?]
        at net.countercraft.movecraft.util.Tags.parseMaterials(Tags.java:125) ~[?:?]
        at net.countercraft.movecraft.combat.features.directors.Directors.load(Directors.java:48) ~[?:?]
        at net.countercraft.movecraft.combat.MovecraftCombat.onEnable(MovecraftCombat.java:71) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:499) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:411) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:430) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:774) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[08:25:08 INFO]: [Movecraft-Combat] Disabling Movecraft-Combat v2.0.0-a.5
```[08:25:08 ERROR]: Error occurred while enabling Movecraft-Combat v2.0.0-a.5 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.THIN_GLASS
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:92) ~[forge:?]
        at net.countercraft.movecraft.util.Tags.parseMaterials(Tags.java:125) ~[?:?]
        at net.countercraft.movecraft.combat.features.directors.Directors.load(Directors.java:48) ~[?:?]
        at net.countercraft.movecraft.combat.MovecraftCombat.onEnable(MovecraftCombat.java:71) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:499) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:411) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:430) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:774) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[08:25:08 INFO]: [Movecraft-Combat] Disabling Movecraft-Combat v2.0.0-a.5
```
What to do?

**Comment by TylerS1066** [comment]
Was fixed in the alpha 5 default config, earlier alphas didn't have the config updated yet.
